package application;

import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.scene.control.TextField;

import javafx.event.ActionEvent;

import javafx.scene.control.TextArea;

import javafx.scene.control.ChoiceBox;

public class mainWindowController {
	@FXML
	private Button help;
	@FXML
	private Button dataSummary;
	@FXML
	private TextArea output;
	@FXML
	private Button allEvents;
	@FXML
	private Button printBy;
	@FXML
	private Button Search;
	@FXML
	private ChoiceBox printByDrop;
	@FXML
	private ChoiceBox searchDrop;
	@FXML
	private TextField searchText;

	// Event Listener on Button[#help].onAction
	@FXML
	public void helpAction(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#dataSummary].onAction
	@FXML
	public void dataSummaryAction(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#allEvents].onAction
	@FXML
	public void allEventsAction(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#printBy].onAction
	@FXML
	public void printByAction(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#Search].onAction
	@FXML
	public void searchByAction(ActionEvent event) {
		// TODO Autogenerated
	}
}
